### ISSUE TITLE
Validation fails if all values are NaN for str type columns

### ISSUE THREAD

**Issue by georgm8** [LTHTR-DST/hdruk_avoidable_admissions#31] opened 2023-02-13 06:14 UTC
As we don't have any values for 'dismeth' the entire column contains NaN values. In this case, Pandas will infer that this column is of type float64. To attempt to pass validation this column can be converted to str type but this means that it still fails validation as the string 'nan' is not included in the accepted values. 

```python
good, bad = validate_dataframe(df, AdmittedCareEpisodeSchema)
# dismeth dtype('str')     [float64] 

df['dismeth'] = df['dismeth'].astype(str)
good, bad = validate_dataframe(df, AdmittedCareEpisodeSchema)
# dismeth  isin({'9', '2', '4', '1', '3', '8', '5'})    [nan]
```

**Comment by vvcb** [comment] 2023-02-13 10:39
Thanks for reporting @georgm8. Duplicate of #19. For unknown/missing values,  use '9' for `dismeth` and '99' for `admisorc` as defined in NHS data model.

**Closed as completed by vvcb** 2023-02-13 10:39 UTC
